import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getCookie } from 'cookies-next'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <a href='/api/google'>LOGIN WITH GOOGLE</a>
    </>
  )
}

export async function getServerSideProps({ req,res}){
  try{
   const cookieExists = getCookie("token", { req, res });
   if(cookieExists) return { redirect: { destination: "/dashboard"}};
   return { props: { }}
  }catch(err){
    return { props: { }}
  }
}
